# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: babbf292ace8a12f734373e108afa2c50eb5b9f4bcd0c81adbad24ae65044c6536a35e0b7590f6d40982cf31e2475a5618550b38ee252e4ffd374f31d9a53fd6

test:
  secret_key_base: 1af9d52d351347e522c9afba378105e9e22c0b49838427dd34dcb46004bdb77b56180429c0f08aa14a8c3bf137556e9c4c1b8cf46af11123411b8b66e9cb3eb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
